export const PREFIX = 'https://fitbox.bounceme.net';
export const loginUrl = '/api/v1/auth/jwt/login';
export const refreshUrl = '/api/v1/auth/auth/jwt/refresh';
export const JWT_STORAGE_KEY = 'jwt_token';
export const registerUrl = '/api/v1/auth/register';
export const logoutUrl = '/api/v1/auth/jwt/logout';
export const GetallusersUrl = '/api/v1/users/';
export const GetallslotsUrl = '/api/v1/slots/';
export const GetoneuserUrl = (id) => `/api/v1/users/${id}`;
export const PatchoneusersUrl = (id) => `/api/v1/users/${id}`;
export const postSlotsBulkUrl = `/api/v1/slots/bulk`;
export const postBookingAdminsUrl = '/api/v1/bookings/by-admin';